### PR TITLE
Profile-page

### PR DESCRIPTION
**Pull request by olowo17**

### CODE REVIEW

**Review by Ehizoba — COMMENTED** [review]
Looks good. Dami will have to finish up first.

**Comment by Ehizoba** [comment]
Please @olowo17 the branch has conflicts; probably you did not pull the latest branch. Kindly resolve or let someone help you

**Comment by Joccso** [comment]
Hello
Please resolve the merge conflict by running `git pull origin develop` on your feature branch.

**Review by taofiq-subair — APPROVED** [review]
Approved.

**Pull request merged**
